# Generated by Django 5.1.7 on 2025-04-02 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0004_alter_session_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='description',
        ),
        migrations.RemoveField(
            model_name='session',
            name='title',
        ),
    ]
