# Generated by Django 5.1.7 on 2025-04-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0005_remove_session_description_remove_session_title'),
    ]

    operations = [
    ]
